#!/bin/sh

case "$1" in 
    start)
        echo "Loading the driver..."
        scull_load
        module_load faulty
        modprobe hello
        echo "Loaded the driver successfully"
        ;;
    stop)
        echo "Unloading the driver scull, faulty and hello"
        scull_unload
        module_unload faulty
        rmmod hello || exit 1
        echo "Unload the faulty successfully"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0